apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: example-signer-role
rules:
- apiGroups:
  - certificates.k8s.io
  resourceNames:
  - example.com/foo
  resources:
  - signers
  verbs:
  - sign
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: example-signer-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: example-signer-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: system
