---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests/status
  verbs:
  - get
  - patch
  - update
# This is an example which allows the signer to sign sample-csr.yaml in the root
# of the repo.
- apiGroups:
  - certificates.k8s.io
  resourceNames:
  - example.com/foo
  resources:
  - signers
  verbs:
  - sign
